<?php
return [
	'groups/add' => 'groups/add',
	'groups/edit/([0-9]+)' => 'groups/edit/$1',
	'groups/remove/([0-9]+)' => 'groups/remove/$1',
	'groups' => 'groups/show',
	'students/add' => 'students/add',
	'students/edit/([0-9]+)' => 'students/edit/$1',
	'students/remove/([0-9]+)' => 'students/remove/$1',
	'students' => 'students/show',
	'subjects/add' => 'subjects/add',
	'subjects/edit/([0-9]+)' => 'subjects/edit/$1',
	'subjects/remove/([0-9]+)' => 'subjects/remove/$1',
	'subjects' => 'subjects/show',
	'marks/add' => 'marks/add',
	'marks/edit/([0-9]+)' => 'marks/edit/$1',
	'marks/remove/([0-9]+)' => 'marks/remove/$1',
	'marks' => 'marks/show',
	'subjectingroup/add' => 'subjectingroup/add',
	'subjectingroup/edit/([0-9]+)' => 'subjectingroup/edit/$1',
	'subjectingroup/remove/([0-9]+)' => 'subjectingroup/remove/$1',
	'subjectingroup' => 'subjectingroup/show',
	'rating' => 'rating/show',
];
